# Generated by Django 4.2.3 on 2023-07-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_remove_student_details_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission_details',
            old_name='registration_No',
            new_name='Reg_no',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Registration_no',
            new_name='Reg_no',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Registration_No',
            new_name='Reg_no',
        ),
    ]
